### ISSUE TITLE
Mesh not rendered if project CRS and layer CRS differ

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/MDAL#108]
If a new mesh layer is added to a qgis project and the project coordinate system (CRS) differ from the newly added layer, then the mesh is not displayed. If then the project CRS is changed (on the fly) to the mesh-layer's CRS, the mesh appears.

Tested with QGIS 3.6

**Comment by saberraz** [comment]
It is related to https://issues.qgis.org/issues/21008

**Comment by PeterPetrik** [comment]
this is purely QGIS bug. The fix requires quite a rewrite of the mesh renderer, and it is already planned and budgeted for 3.14
