### ISSUE TITLE
Problem opening hydro_as-2d dataset when mesh has gaps in vertex indexing

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#112]
Example data sent to @PeterPetrik

**Comment by PeterPetrik** [comment]
Looks like in the file the number of nodes is 56701, but DEPTH.dat states it stored data for 57719 entries. The dat file is hence inconsistent with the mesh 

```
peter@pp-mb:~/GIS/MDAL/bugs/bug_MDAL_112$ grep -rn E4Q hydro_as-2d.2dm | wc -l
   55639
peter@pp-mb:~/GIS/MDAL/bugs/bug_MDAL_112$ grep -rn ND hydro_as-2d.2dm | wc -l
   56701
peter@pp-mb:~/GIS/MDAL/bugs/bug_MDAL_112$ grep -rn ND DEPTH.dat 
DEPTH.dat:2:ND  57719
```

**Comment by PeterPetrik** [comment]
error reporting should be improved by #102

**Comment by saberraz** [comment]
The same files were opened successfully in QGIS 2.18 using old Crayfish

**Comment by PeterPetrik** [comment]
The problem was when the 2DM mesh uses gaps in vertex numbering. This is pretty much only used in hydro_as-2d AFAIK.
