### ISSUE TITLE
Basement v3.0 xmdf couldn't render spec. discharge as vector

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/MDAL#115]
When loading Basement v3.0 results (xmdf) into QGIS, `spec_discharge`  is recognized as a vector (Groups displays an arrow). Nevertheless `Show vectors` is grayed out. Am I missing something?

**Comment by kastepha** [comment]
In my example case displaying of vectors for spec. discharge works fine. Did you check the "Show Vectors" field in the Vector tap?

**Comment by michelk** [comment]
When I simulate the [tutorial case](http://www.basement.ethz.ch/download/tutorials/tutorials3.html), I get the following results:

[Github_spec-discharge_issue.zip](https://github.com/lutraconsulting/MDAL/files/3116044/Github_spec-discharge_issue.zip)

But QGIS 3.6.2 show me


![groups](https://user-images.githubusercontent.com/1404919/56723436-3e7a8080-6749-11e9-9dc9-8c57f417e368.png)

and 

![show-vectors](https://user-images.githubusercontent.com/1404919/56723437-3f131700-6749-11e9-9b5d-48710c32e689.png)

**Comment by PeterPetrik** [comment]
Can you try to click on the small "arrow" symbol in the groups menu? 
<img width="351" alt="Screenshot 2019-04-25 at 11 07 18" src="https://user-images.githubusercontent.com/804608/56723964-556da280-674a-11e9-983a-5743107192af.png"> and then adjust in vector settings?

**Comment by kastepha** [comment]
@michelk I tested your dataset, visualization of vectors works fine. But you need to click on the arrow like Peter mentioned.

**Comment by michelk** [comment]
Found it out. 

I had to click on the arrow in the groups tab.

![vector-click](https://user-images.githubusercontent.com/1404919/56726117-7506ca00-674e-11e9-8363-841ecc6271eb.png)

**Comment by michelk** [comment]
My browser wasn't refreshing ;).

Thanks.
