### ISSUE TITLE
Editing/Creating Mesh 

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#121]
Right now we have only possiblity to load mesh, but we are not able to edit it. Similarly we have API for dataset to both read and write. 

It would be nice to add API to be able to create empty mesh, add some vertices and faces to it.  For beginning we can implement 2dm files writer, so we would be able to persist the new/edited mesh back to 2dm file.

**Comment by vcloarec** [comment]
Have you chosen the 2dm format because it is the simplest ?

**Comment by PeterPetrik** [comment]
yep, 2dm is the ASCII format, well defined and easiest for beginning.

**Comment by vcloarec** [comment]
Ok, but is this file format is the one which have the most interest to be edited ? 
I don't know this format, but is this format is needed to be created and edited by user ?
Just questions, I really don't know.

**Comment by vcloarec** [comment]
What ate the TIN file formats used by hydraulic models ?

**Comment by PeterPetrik** [comment]
The API for write will be the same for all drivers that have capability to write/edit meshes. To begin actual implementation, I think it is easiest to start with 2dm since it is ASCII format and one can check result in text editor

2dm is used in various models , e.g. TUFLOW, HECRAS, BASEMENT, ...

**Comment by vcloarec** [comment]
Back to editing mesh after couple weeks, I have implemented a simple 2dm writer. #

**Comment by vcloarec** [comment]
#

**Comment by vcloarec** [comment]
Editing mesh (e.g. add vertices or faces) needs to have a good handle of the vertices and faces arrangement and it is not trivial. I don't know if the aim of MDAL is to handle this arrangements... If yes, there is a lot of work to do.
If not necessary, there is a need for third library to handle properly this arrangement, but license is may be not compatible to make MDAL dependent from it.
I am thinking about [CGAL](https://doc.cgal.org/latest/Manual/packages.html#PartTriangulationsAndDelaunayTriangulations) or [Jonathan Richard Shewchuk's code](https://www.cs.cmu.edu/~quake/triangle.html) to generate triangulation.
An other way could may be that MDAL offers sort of interface to derive from some generator/arrangements engines. So the users can implement engines to generate/edit mesh and use MDAL to open/save and to display mesh with QGIS.
What do you think about?

**Comment by PeterPetrik** [comment]
I think that this ticket assumes that you create vertices/faces externally and MDAL just have api to modify the mesh frame. So in first stage I assume we do not need triangulation library.
