### ISSUE TITLE
Wrong parsing of times in Hec-RAS files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#125]
Time steps (and hence total simulation length) is reported incorrectly in MDAL.

**Comment by PeterPetrik** [comment]
@saberraz which file. for that file, what is the correct time?

**Comment by PeterPetrik** [comment]
e.g. in HECRAS_1_2D/Piberbach_Ausbaube.p02.hdf
medatata there is : Run Time Window -> `27MAR2019 11:48:23 to 27MAR2019 13:14:30`
but in QGIS maximum time is `27.3.2019 12:03:23`
