### ISSUE TITLE
Add a c++ entry to MDAL for editing mesh

### ISSUE THREAD

**Issue by vcloarec** [lutraconsulting/MDAL#136]
Mesh editing (add/remove vertices, flip faces, refine mesh,...) needs to handle correctly the change of the arrangement between faces and vertices, eventually with hard lines (constraint lines).

This is not trivial, and it would be quite complex and long to implement it in the MDAL API. But some libraries can help to handle this arrangement. Those libraries handle directly the arrangement between faces and vertices in their own way in memory or files. 
To avoid right now to add dependencies, a simple and convenient way to obtain a compatible mesh with these libraries and with MDAL is to derive the MDAL::Mesh class. The derived classes could wrap the mesh handled by the third library. This derived classes would be external to MDAL, so no dependencies for MDAL, and the user of the derived classes can choose for his code the license compatible with MDAL license and the third library license.
Opening and saving this mesh would be possible with MDAL, and the arrangement would be handled by the third library.

But today, the MDAL::Mesh is not open to be derived externally. It will be convenient to add an C++ entry for this class, maybe with one of these solutions :
- make MDAL::Mesh exported
- implement a exported class derived from MDAL::Mesh, this new class would be adapted to be exported without exposing too much MDAL::Mesh (I don't know if there are some reasons to not expose some parts of MDAL::Mesh).

**Comment by PeterPetrik** [comment]
MDAL has plain C API to keep compatibility with all possible interfaces (python, r, c++, ...)

I prefer if external library prepares vertex + face list with coordinates and then just calls MDAL C-API to insert these coordinates to the mesh.
