### ISSUE TITLE
Mesh Calculation does not regconize parameters in UGRID NetCDF

### ISSUE THREAD

**Issue by dquang** [lutraconsulting/MDAL#144]
The mesh calculation accepts only "Bed Elevation" as a valid parameter, while others ("Water level", "Cell_area"...) are not accepted. This problem seems only happen with UGRID NetCDF from Delft3D-FM.

**Comment by PeterPetrik** [comment]
Please open the ticket in qgis/QGIS issue tracker, mesh calculator is function of QGIS. 
also note that the mesh calculator support only datasets defined on nodes/vertices are supported ATM.

https://github.com/qgis/QGIS/blob/master/src/analysis/mesh/qgsmeshcalculator.h#L44
