### ISSUE TITLE
Support for DHI nc file

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#146]
DHI SDK converts their format to netcdf. At least, we can support this format while waiting for @DHI to open up their formats for others to use them.

**Comment by PeterPetrik** [comment]
@saberraz can you attach some small test file for our test suite ?

**Comment by saberraz** [comment]
Attached is the netcdf schema:
[NetCDF_Schema.txt](https://github.com/lutraconsulting/MDAL/files/3574822/NetCDF_Schema.txt)

**Comment by PeterPetrik** [comment]
@saberraz I need some test example if you want this to be part of 0.5.0 (qgis 3.12)

**Comment by saberraz** [comment]
I think we can park this due to the lack of cooperation from https://github.com/DHI

**Comment by PeterPetrik** [comment]
native driver implemented with help of DHI, https://github.com/lutraconsulting/MDAL/pull/377/files 🎉
