### ISSUE TITLE
Add support for reading arcinfo adf tin layers

### ISSUE THREAD

**Issue by nyalldawson** [lutraconsulting/MDAL#162]
GDAL/OGR has support for reading arcinfo binary vector and raster layers, but not adf tin layers. Seems like a perfect fit for mdal...

**Comment by vcloarec** [comment]
As a former user of Esri TIN, I am very tempted to do the work... 
Have you got a recent Esri TIN to provide? As I don't use those format for years, I don't have one.

**Comment by nyalldawson** [comment]
I can provide a few, but not ones which could be publicly shared, sorry. Want me to email them?

**Comment by vcloarec** [comment]
yes, it would be great for first trials. But not too big please.
Then we need some which can be publicly for tests.

**Comment by nyalldawson** [comment]
What's your email @vcloarec ?

**Comment by vcloarec** [comment]
Sorry, you can use this one : vcloarec@reos.site

**Comment by vcloarec** [comment]
On the good way : can read the (x,y,z) of the node.

**Comment by saberraz** [comment]
Good overview of the format and specifications, with link to other resources:
https://en.wikipedia.org/wiki/Esri_TIN

**Comment by PeterPetrik** [comment]
I am wondering if this format is ONLY mesh definition or if it has any datasets? If there are no datasets defined on mesh, I am not sure if it not rather part of GDAL/OGR instead of mesh

Wondering where we can get some examples @saberraz do we write to ESRI to provide some or are there any freely available?

**Comment by PeterPetrik** [comment]
also @nyalldawson can you please share some test data with us on info@lutraconsulting.co.uk please?

**Comment by wonder-sk** [comment]
> I am wondering if this format is ONLY mesh definition or if it has any datasets? If there are no datasets defined on mesh, I am not sure if it not rather part of GDAL/OGR instead of mesh

Even if it is only mesh without any extra datasets, it still makes sense to have native support in MDAL for such TINs - GDAL/OGR would need to convert the triangles to a regular grid, loosing some data during the conversion...

**Comment by saberraz** [comment]
An example TIN here:
https://github.com/usgin/Workshops/tree/master/GeothermalResourcesCouncil/MeetingProjects/Arc3D/Bangor_3D/top

No licence according to @ccaudill

**Comment by PeterPetrik** [comment]
no problem, but the limitation will be the `int` (https://github.com/lutraconsulting/MDAL/blob/master/mdal/api/mdal.h#L222) since we internally need to index vertices/faces.

**Comment by nyalldawson** [comment]
The int limitation won't impact this - the format has a built in limit of storing the vertex count in an int anyway

**Comment by vcloarec** [comment]
> Even if it is only mesh without any extra datasets, it still makes sense to have native support in MDAL for such TINs - GDAL/OGR would need to convert the triangles to a regular grid, loosing some data during the conversion...

agree, I think TIN are important member of the mesh family. A particular member but very useful.
