### ISSUE TITLE
mdal_translate utility

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#167]
create mdal2mdal utility to convert between various formats

**Comment by saberraz** [comment]
Also expose it to QGIS, so we can have a processing in QGIS/Crayfish through the Processing Toolbox.

**Comment by PeterPetrik** [comment]
docs: 

to convert 2dm to ugrid mesh, 

``` mdal_translate -of Ugrid mesh.2dm dest.nc```

**Comment by Veethahavya** [comment]
Hello @PeterPetrik , this is a very helpful tool for me right now. However, I see that the file is converted to CF-1.6 UGRID-1.0 format that is missing the characteristic coordinates of the mesh ('mesh2d_face_x', 'mesh2d_face_y') as per the CF-1.8 UGRID-1.0 Deltares-0.10 convention.
I am using mdal-0.7.4.
Is there any way I could modify the driver to translate the .2dm file to the CF-1.8 UGRID-1.0 Deltares-0.10 format with the following variables:
(['projected_coordinate_system', 'mesh2d', 'mesh2d_node_x', 'mesh2d_node_y', 'mesh2d_node_z', 'mesh2d_edge_x', 'mesh2d_edge_y', 'mesh2d_edge_nodes', 'mesh2d_face_nodes', 'mesh2d_edge_faces', 'mesh2d_face_x', 'mesh2d_face_y', 'mesh2d_face_x_bnd', 'mesh2d_face_y_bnd'])
Or are there any other tools that you know of that I could make use of for this case?
Any help is highly appreciated. Thanks in advance.
Cheers!
