### ISSUE TITLE
Check default time units in selafin files

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#185]
http://www.opentelemac.org/downloads/Archive/v6p0/telemac2d_user_manual_v6p0.pdf
is not specific whether time is in hours or seconds, 

```
Appendix 3: page 118: 
Next, for each time step, the following are found:-  1 record containing time T (real),
```

so far we are parsing this time as hours.

@ccoulet do you know if timesteps in QGIS are correct, or the default is hours and the timesteps are not as in other softwares?

**Comment by PeterPetrik** [comment]
#179 changed it to seconds, so I am wondering whether to revert it back

**Comment by ccoulet** [comment]
Hi
Time in telemac selafin file is in seconds.
It's wrong in QGIS
regards
