### ISSUE TITLE
Design logo 

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#192]
for documentation, website, presentations, ...

**Comment by nyalldawson** [comment]
Ping @nirvn... Another opportunity for a unified branding set!!

**Comment by PeterPetrik** [comment]
Happy to present new MDAL logo!

![LogoVertical_01_color](https://user-images.githubusercontent.com/804608/76337407-9b4a3f80-62f7-11ea-893e-0ae30e2feef6.png)

**Comment by nirvn** [comment]
@PeterPetrik , really great looking!

**Comment by saberraz** [comment]
![MDAL_logo_manual1](https://user-images.githubusercontent.com/2649047/76340826-1e699680-62f4-11ea-9eeb-0abd2abb2ad9.png)
![MDAL_logo_manual2](https://user-images.githubusercontent.com/2649047/76340843-2295b400-62f4-11ea-977f-8da5f975b84f.png)

**Comment by PeterPetrik** [comment]
all credits to [Rado Marcek](https://www.linkedin.com/in/radovan-marček-34091524/)
