### ISSUE TITLE
No velocity arrows for Hec RAS data

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#197]
When adding this mesh layer in QGIS:
https://github.com/lutraconsulting/MDAL/blob/master/tests/data/hec2d/2dmodel_5.0.5/temp.p01.hdf

The **Face Velocity** dataset should contain velocity arrows.

**Comment by PeterPetrik** [comment]
From h5dump it seems that both Face Velocity and Face Sheer Stress are scalar values. 

```
                           DATASET "Face Velocity" {
                              DATATYPE  H5T_IEEE_F32LE
                              DATASPACE  SIMPLE { ( 61, 114 ) / ( H5S_UNLIMITED, 114 ) }

                           DATASET "Face Shear Stress" {
                              DATATYPE  H5T_IEEE_F32LE
                              DATASPACE  SIMPLE { ( 61, 114 ) / ( H5S_UNLIMITED, 114 ) }
```

@erpas Can you confirm that Face Velocity is scalar?

**Comment by erpas** [comment]
According to HEC-RAS 2D Manual:
![obraz](https://user-images.githubusercontent.com/3106699/72138477-302ecc00-338d-11ea-8500-b0e9e1c041c2.png)
