### ISSUE TITLE
support for stl,ply,obj,vtk meshes

### ISSUE THREAD

**Issue by AndrewAnnex** [lutraconsulting/MDAL#209]
I am using geomodeling software to produce 3d triangular meshes that I currently view within paraview, but I would like to be able to view these files within QGIS eventually so it would be great to support more conventional 3d formats in MDAL (and by extension QGIS 3d viewer). I would suspect some issues, these formats are not geospatially aware as far as I know, so there would be a question about CRSs and how these formats would deal with it. Otherwise tutorials could be provided to convert these formats into those compatible with MDAL

**Comment by wonder-sk** [comment]
hi @AndrewAnnex thanks for the feedback. I am wondering what kind of formats does your geomodelling software produce (by the way I am also curious about what kind of modelling do you do). Maybe we could have support for the native format so there would be no need for formats like stl/ply/obj (that are good for 3D graphics, but I am not sure if they fit well into the MDAL data model).

Maybe you could try to use 2DM format. That format is human readable and easy to read/write. A sample file that contains a sample triangle and a quadrilateral can be found here:
https://github.com/lutraconsulting/MDAL/blob/master/tests/data/2dm/quad_and_triangle.2dm

Essentially you first define vertices with "ND" lines and then elements with E3T and E4Q lines, using indices of vertices (starting from one). You should be able to load that sample file in QGIS >= 3.4
as a mesh layer.

Full format specification is here:
https://www.xmswiki.com/wiki/SMS:2D_Mesh_Files_*.2dm
(please note that MDAL does not support all features from the format)

**Comment by AndrewAnnex** [comment]
hey @wonder-sk, so I am specifically using https://github.com/cgre-aachen/gempy to produce the models. That library/a number of other open source projects in the foss 3d geomodeling/vis world seem to rely on VTK formats (vtk.org, kitware) for which there are a number of flavors. I also use the pyvista project to view these mesh files and uses https://github.com/nschloe/meshio that could allow me to convert to other 3d data types (maybe tin) but I am not sure if these data types are really 1:1 equivalent yet. There are also more common/modern? 3d formats like collada and gITF https://en.wikipedia.org/wiki/GlTF.

Does the OGC has a standard in place for geospatial 3d meshes?

**Comment by wonder-sk** [comment]
Thanks for the links. There seem to be few formats that are supported both by MDAL and meshio (xdmf, ugrid) so it could be useful to try to convert to those using meshio.

MDAL was originally designed mainly for 2.5D meshes used in flood modelling and the aim was to support display of many different quantities stored on vertices or faces. But there's nothing that would stop us from supporting also true 3D meshes from different full-fledged 3D formats like vtk, stl, obj or others. If VTK is popular in geomodelling, it would be good to have at least some basic support for it (it's pity the format has more variants and it can get quite complex).

I have seen the formats like stl/obj/ply used mostly as a way to store simple 3D objects without any geographic reference (a model of a tree, bench, street lamp etc.) but if they are used also in the context of geo-data, with coordinates corresponding to a particular known coordinate reference system, it would be interesting to load them as mesh layers (any sample data?)

By the way, QGIS 3D map view supports rendering of points in map layers as 3D models loaded from a 3D mesh (obj, stl, collada etc - essentially whatever assimp library supports). See e.g. here: https://gis.stackexchange.com/questions/306038/what-kind-of-3d-models-can-qgiss-3d-view-handle

> Does the OGC has a standard in place for geospatial 3d meshes?

I am aware of 3D Tiles standard: https://www.opengeospatial.org/standards/3DTiles - developed by the community around Cesium project. It supports several kinds of 3D data and meshes are encoded using glTF standard (if I remember correctly).

**Comment by AndrewAnnex** [comment]
thanks @wonder-sk I agree with your observations of stl/obj/ply. There are a lot of 3d formats out there and I am certainly not familiar with all of them. VTK seems to be more popular for computational physics and biomedical imaging from things I have seen, other 3d formats from the geomodeling community seem to be semi proprietary to particular platforms that exist (leapfrog, petrel, etc). It is interesting to attempt to use those more common formats as they play nicer with MacOS and Windows which can generate thumbnail previews/load into powerpoint etc. 
Hence my suggestion for something more mainstream like obj/ply/stl/gTIF, as different subfields have their own niche formats that can be converted to more common formats. I don't have sample data on hand at the moment for stl/obj/ply that is small/easy but it should be easy to find a SRTM DEM tile and convert it to one of these mesh data types.  

I will check the native support for 3d models but I suspect that my data wont play well with it. I can update once I have the chance to try it out.

**Comment by PeterPetrik** [comment]
discussed and we can go forward by support of https://github.com/lutraconsulting/MDAL/issues/216 for the beginning
