### ISSUE TITLE
Netcdf support

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#22]
It will be good to add support for netcdf:
https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/corelib/frmts/crayfish_netcdf.h

https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/test/data/NetCDF/indonesia_nc4.nc?raw=true
https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/test/data/NetCDF/indonesia_nc3.nc?raw=true

**Comment by PeterPetrik** [comment]
fixed in 0.0.9 release
