### ISSUE TITLE
xdmf from Basement causes core dump in QGIS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#226]
2dm opens fine, but when I try to attach the xdmf it crashes QGIS with the attached log:
[core_dump.txt](https://github.com/lutraconsulting/MDAL/files/4305039/core_dump.txt)

**Comment by saberraz** [comment]
And here is the result of `mdalinfo`

```
mdalinfo 0.4.90
Mesh File: Flaz_mesh.2dm
Mesh loaded: OK
  Driver: 2DM
  Vertex count: 7446
  Face count: 14457
  Projection: undefined
Dataset File: results.xdmf
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140654747844480:
  #000: ../../../src/H5F.c line 370 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: ../../../src/H5Fint.c line 802 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: ../../../src/H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'results.xdmf/results.h5', errno = 20, error message = 'Not a directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
Segmentation fault (core dumped)
```

**Comment by PeterPetrik** [comment]
0.4.90 is very strange version. (x.y.9z means development version). can you either try with the official QGIS release, or with the current development version 0.5.90?

**Comment by qqplot1988** [comment]
I have try to install the version 0.5.90 from the zip file (MDAL-0.5.90.zip) on the manager of the plugins. I have the following error:.

ModuleNotFoundError: No module named 'MDAL-0' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'MDAL-0'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.0-București București, cd141490ec 

Am I doing something wrong for installing the mdal 0.5.90?

Cheers,

**Comment by PeterPetrik** [comment]
MDAL is not a python plugin, it is core data provider. Can you try to test the problem with the official QGIS release?

**Comment by qqplot1988** [comment]
Ok. I have download Qgis 3.12 from the official release (https://www.qgis.org/fr/site/forusers/download.html). How can I correct this?

**Comment by saberraz** [comment]
Just install QGIS and try to open the 2dm and then attach the XDMF. MDAL is shipped with QGIS.

**Comment by qqplot1988** [comment]
It’s what I did but I have the following error mention upstream.

**Comment by saberraz** [comment]
In master (both QGIS and MDAL), it does not crash any more. But comes up with "Cannot open the data source".

Here is the error from terminal:
```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140570471417024:
  #000: ../../../src/H5Gdeprec.c line 291 in H5Gopen1(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: ../../../src/H5Gint.c line 318 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../../src/H5Gloc.c line 378 in H5G__loc_find_cb(): object 'TIMDEP NETCDF OUTPUT RESULTS' doesn't exist
    major: Symbol table
    minor: Object not found

```

**Comment by qqplot1988** [comment]
Hi,

With the last version or Basement (version 3.0.2), with Qgis 3.12 I have the error: Could not read mesh dataset for the xdmf file.

The link to download the data is:
https://www.webtransfer.ch/fr/download/73cf8ba4012cf8bcc47c38c49fa6a51eaa50151c

Cheers,

**Comment by qqplot1988** [comment]
Problem is solved. It was a problem with the path of the file.

**Comment by Pips-PPC** [comment]
How did you solve it? Did you change the path?

I have the same problem with the same QGIS version (3.12) and BASEMENT (3.0.2) version.

**Comment by mattfack** [comment]
Pips-PPC try to change the path in the xmdf file like this: 
put all your bm files (xdmf, h5 and 2dm) in one folder, open the xdmf with a text editor and change all the absolut paths to just the name of the file (D:\path\to\results\results.h5 sould become only results.h5). see here: http://people.ee.ethz.ch/~basement/forum/viewtopic.php?pid=6090#p6090

cheers

**Comment by saberraz** [comment]
Let's reopen and get it sorted in MDAL. We can fix it while BASEMENT introduces a new format and breaks everything :(

**Comment by mattfack** [comment]
It's not a matter of format introduced by BASEMENT: it is a problem with the path in the xdmf file. It is not BASEMENT-related.

**Comment by saberraz** [comment]
where can we find the format spec for xdmf?

**Comment by qqplot1988** [comment]
Yes it the xdmf file, there is a link to the reslus.aux but with the link of the folder. If you move this, it doesn't work. It's a problem from de basement team who will solve it for the next version.

http://people.ee.ethz.ch/~basement/forum/viewtopic.php?id=5261

You can close it.
