### ISSUE TITLE
Display problem when rotating the window

### ISSUE THREAD

**Issue by ccoulet** [lutraconsulting/MDAL#232]
I can display my results without any problem but when I rotate the image some display problems appear.
From few small hole à 5° to a full disapear at 50°.
Tested in 3.12...
Is this a known problem of MDAL or is there a solution?

Regards

**Comment by saberraz** [comment]
I can confirm the issue. This is a QGIS issue for displaying and rendering the mesh. MDAL is for reading/writing the mesh.

I have filed an issue here:
https://github.com/qgis/QGIS/issues/35147
