### ISSUE TITLE
Some Selafin files fail to load

### ISSUE THREAD

**Issue by csibk** [lutraconsulting/MDAL#276]
Thanks for bringing mesh support to QGIS. This will help us in in our workflow around Telemac2D.

Unfortunately many of our selafin files fail to open in QGIS using the add mesh layer functionality. This was tested with the just released 3.14 under Ubuntu 18.04 and 20.04. Some files that cannot be opened with mdal can be opened with the ogr driver but are distorted.

We use different tools to create selafind (double precision) files.

This is an overview of working/non working selafind meshes:

1) preprocessing using BlueKenue (V3.9.5): files can be opened in QGIS as a mesh layer
2) preprocessing using Janet (V2.24): files cannot be opened in QGIS as a mesh layer
3) outputfile telemac2d (Vv7p2r0) with model preprocessed by BlueKenue: files cannot be opened in QGIS as a mesh layer
4) outputfile telemac2d (Vv7p2r0) with model preprocessed by Janet: files cannot be opened in QGIS as a mesh layer

Below is some logging information from QGIS when started from terminal

case 1)

    ../../src/app/qgisapp.cpp:5539 : (addMeshLayerPrivate) [61617ms] completeBaseName: test_sd_1

case 2)

    ../../src/app/qgisapp.cpp:5539 : (addMeshLayerPrivate) [48251ms] completeBaseName: test_sd_2
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_2.slf' not recognized as a supported file format.
    ERROR: Status 3: Unable to load mesh (null)

case 3 and 4)

    ../../src/app/qgisapp.cpp:5539 : (addMeshLayerPrivate) [18895ms] completeBaseName: test_sd_4
    ERROR: Status 3: Driver: SELAFIN: File format problem while reading double array
    ERROR 4: `test_sd_4.slf' not recognized as a supported file format.
    ERROR 4: `test_sd_4.slf' not recognized as a supported file format.
    ERROR: Status 3: Unable to load mesh (null)

On request we can provide additional information and try to create example files.

**Comment by PeterPetrik** [comment]
Hi, 

could you please create and attach the example files (ideally smaller than 3MB) suitable for our automatic test suite? Without the possiblity to reproduce the issue, we are unable to create a fix

Thanks.
Peter

**Comment by csibk** [comment]
Hello Peter,

sure. The attached zipfile contains three testfiles and a README.TXT with some additional information about each file. The testfiles are not the ones from the initial report but all fail to load in QGIS 3.14.

Christian

[selafin_test_files.zip](https://github.com/lutraconsulting/MDAL/files/4864646/selafin_test_files.zip)

**Comment by vcloarec** [comment]
Hello @csibk,
Can we use those files to include them to the automatic test suite?

**Comment by csibk** [comment]
@vcloarec: yes, you can include them. My coworker created them specifically for this ticket.
