### ISSUE TITLE
Add mesh translation (TELEMAC2D)

### ISSUE THREAD

**Issue by nicogodet** [lutraconsulting/MDAL#285]
Hello, 

When performing simulation with TELEMAC2D, we often shift the mesh in X/Y to avoid truncation of coordinates (single precision files).

Enhancement : Add dX/dY options to reproject the mesh.

**Comment by PeterPetrik** [comment]
I assume this would be probably the processing algorithm in QGIS?

**Comment by nicogodet** [comment]
I didn't even thought about the existing algorithm but could be an alternative to what I expect.

Initially, I excepted 2 options (dX and dY) in layer's properties near CRS param and translation would be done on the fly and stored in memory.
When a project is saved, dX/dY are saved too. When a project is opened, if dX/dY are set, translation is done and stored in memory.

The behavior I describe here is the same that Artelia defined in [PostTelemac plugin](https://github.com/Artelia/PostTelemac). I know that Artelia plan to update this plugin with MDAL backend.

**Comment by vcloarec** [comment]
@nicogodet , this translation make me think about the origin parameters in the Selafin file. With this origin different from (0,0) you could have this translation. But I don't know how your workflow could integrate this origin in the Telematic files...

**Comment by nicogodet** [comment]
For now, our post-processing workflow is exclusively based on PostTelemac (visualisation, flow computation, node extraction, temporal graph and evolution).
We import the result file as a meshlayer when we want a nice visualisation (velocity traces especially) or for animation's creation.

**Comment by ccoulet** [comment]
@nicogodet Instead of shift the mesh, you could declare the local 0,0 in the selafin header (easy to do with BlueKenue) and everythings goes well for the visualization in Qgis with MDAL.

**Comment by nicogodet** [comment]
@ccoulet Thanks for the tips !

**Comment by PeterPetrik** [comment]
I am getting a bit lost here. In case there is some (translation?) in the original source file that MDAL does not read/ignore, can you describe it and we can fix it /implement it. In case MDAL reads it OK, but you want to translate the mesh somewhere, best to close this ticket and open feature request in QGIS repository. In that case we can either A) create processing algorithm to translate the mesh data somewhere  (quite easy to implement in case we have writer for that particular format) or B) some on-the-fly rendering setting to translate the mesh (more difficult)

**Comment by nicogodet** [comment]
@PeterPetrik, regarding Christophe comment, it looks like MDAL is reading selafin file correctly (I haven't tried yet).
So this issue could be closed.

The feature request could be interresting in case an existing file does not have the local 0,0 declared in header and B) option would be the best as we keep the original file intact and don't create another one which is translated.
