### ISSUE TITLE
[SELAFIN] unable read Fudaa-prepro selafin export

### ISSUE THREAD

**Issue by nicogodet** [lutraconsulting/MDAL#286]
[Fudaa-prepro](https://fudaa-project.atlassian.net/wiki/spaces/PREPRO/overview) is used for pre and post processing of TELEMAC2D model.

I have an "invalid string position" when importing a mesh exported from fudaa (see attached file).
Qgis 3.14.1

[export_fudaa.zip](https://github.com/lutraconsulting/MDAL/files/5006839/export_fudaa.zip)

**Comment by vcloarec** [comment]
Hello,
It seems that the precision (simple or double float, express by "SERAFIN" or "SERAFIND" in the header of the file) is not specified in this file.
If, I "hack" this precision specification, I can read the file.
I don't now if TELEMAC format support officially that this precision specification is not present. If you have this information, we can fix this issue.

**Comment by nicogodet** [comment]
Using Fudda, we extract a specific time step of a simulation to set initial condition of another simulation.
So TELEMAC support it.

I don't know exactly how telemac detect the precision of the file, maybe it reads the 8th character only (empty : single precision, "D" : double precision ) ?
poke @ccoulet

**Comment by ccoulet** [comment]
In fact, there was a decision to indicate the type of Telemac file in the header of the file (the last 8 characters) but we know that Fudaa didn't implement that decision for the moment (In fact, there is no recent development on Fudaa!)
This is not a real problem for Telemac itself because an algorithm was implemented to determine the kind of file we are dealing with... So selafin file generated by fudaa could be used by Telemac without any problem but aren't recognize by MDAL...

**Comment by vcloarec** [comment]
Thanks @ccoulet for this precision. Does it make sens to consider simple precision by default?

**Comment by nicogodet** [comment]
Fudaa set the last character of the header to "D" if it's a double precision selafin and leave it empty for single precision.

I can provide a double precision export if you want to.

**Comment by ccoulet** [comment]
@vcloarec yes it could be an option.
To be more precise in telemac the simple/double kind of a selafin file is evaluate from the length of the record which contains coordinates of nodes (the number of node is read few records before).

**Comment by PeterPetrik** [comment]
> I can provide a double precision export if you want to.

Please do if you can

**Comment by nicogodet** [comment]
[export_fudaa_doublePrecision.zip](https://github.com/lutraconsulting/MDAL/files/5055182/export_fudaa_doublePrecision.zip)

**Comment by nicogodet** [comment]
Is this issue planned to be fixed before Qgis 3.16 is released ?

**Comment by PeterPetrik** [comment]
Hi, unfortunately we are quite busy and we haven't planned this bugfix for 3.16. If you create PR, I can review and merge to QGIS 3.16. Or alternatively, if you need it for 3.16, please consider commercial support "Small Office" (https://www.lutraconsulting.co.uk/support/).

**Comment by nicogodet** [comment]
I could give it a try but it will be an ugly fix...
"SELAFIN" or "" -> Single precision
"SELAFIND" or "D" -> Double precision
in https://github.com/lutraconsulting/MDAL/blob/master/mdal/frmts/mdal_selafin.cpp#L201L226

**Comment by vcloarec** [comment]
@nicogodet , as nothing or D is not an official specification, a proper solution could be to use the Telemac way:

> the simple/double kind of a selafin file is evaluate from the length of the record which contains coordinates of nodes

**Comment by nicogodet** [comment]
I agree ! That's why I called my fix ugly.
Unfortunately I can't propose a PR based on Telemac way.

**Comment by nicogodet** [comment]
Hi @PeterPetrik,

This issue is very specific and focused on Single/Double precision.
I noticed this morning, using Telemac V8P2 python scripts `run_selafin.py`, that MDAL is too strict when it reads headers of SELAFIN file.
I assume that `run_selafin.py `output is a valid SELAFIN and Qgis can't read it "Invalid data source" (btw MDAL throws an explicit error like `throw MDAL::Error( MDAL_Status::Err_UnknownFormat, "File format problem while reading connectivity table" );` but error message in Qgis is always `CRITICAL    Invalid Data Source : $File is not a valid or recognized data source.` but this is another issue)

Similar issue when using unofficial python library PPutils which is based on TELEMAC scripts -> https://github.com/pprodano/pputils/blob/master/ppmodules/selafin_io_pp.py

But newly created files (from both official scripts and unofficial ones) are valid since I re-use them in another simulations.

Should I open a new issue "Make MDAL less strict when reading headers" or should we keep this one open ?

Following link give you access to SELAFIN files modified using `run_selafin.py alter` : https://cloud.nicodet.fr/s/grGiF6e67tm29St
File's names are explicit.
_lastT and _lastT_bottomOnly leave header untouched -> Qgis can open them.
_lastT_modifFloat and _lastT_modifTitle affect header -> Qgis can't open them.

**Comment by PeterPetrik** [comment]
this ticket is good enough. Feel free to create a propose a proper PR we are able to merge. Otherwise we are happy to provide a commercial quote for implementation of this bugfix, if you can contact us on info@lutraconsulting.co.uk
