### ISSUE TITLE
Support for copy/paste and duplicate actions for mesh layers within QGIS

### ISSUE THREAD

**Issue by Brent-Edwards** [lutraconsulting/MDAL#290]
Currently, the "duplicate layer" action yields the following warning :

> Duplicate layer: <the_mesh_layer_name> ( type unsupported)

Copy/paste yields an "empty layer" without warning. It would be great to support these actions along with the "copy style" functionality.

Here's my QGIS version info:

> QGIS version
> 3.14.1-Pi
> QGIS code revision
> de08d6b71d
> Compiled against Qt
> 5.11.2
> Running against Qt
> 5.11.2
> Compiled against GDAL/OGR
> 3.0.4
> Running against GDAL/OGR
> 3.0.4
> Compiled against GEOS
> 3.8.1-CAPI-1.13.3
> Running against GEOS
> 3.8.1-CAPI-1.13.3
> Compiled against SQLite
> 3.29.0
> Running against SQLite
> 3.29.0
> PostgreSQL Client Version
> 11.5
> SpatiaLite Version
> 4.3.0
> QWT Version
> 6.1.3
> QScintilla2 Version
> 2.10.8
> Compiled against PROJ
> 6.3.2
> Running against PROJ
> Rel. 6.3.2, May 1st, 2020
> OS Version
> Windows 10 (10.0)
> Active python plugins
> BASEmesh; 
> changeDataSource; 
> crayfish; 
> gmsh; 
> LAStools; 
> latlontools; 
> profiletool; 
> quick_map_services; 
> splitmultipart; 
> SVG2ColoR; 
> valuetool; 
> VoGisProfilTool; 
> db_manager; 
> processing

**Comment by PeterPetrik** [comment]
Hi @Brent-Edwards, I have created a QGIS ticket for this feature request (bug?), since it is not related to MDAL data handling, but rather the QGIS functionality.
