### ISSUE TITLE
Add support for AnuGA output

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#30]

**Comment by saberraz** [comment]
This will include:
-          Elevation for Erosion
-          Friction for Depth Varying Friction
-          Sediment for Sediment Transport
-          Any other User defined…. etc

**Comment by PeterPetrik** [comment]
@saberraz can you please give me a simple small test case with couple of timesteps and cells with all that we should be able to parse? (ideally <3-5mb)

**Comment by saberraz** [comment]
CC 	@RudyFrom3 ??

**Comment by PeterPetrik** [comment]
ported code from crayfish 2.x.
