### ISSUE TITLE
Error in GRIB when built against GDAL 3.1.3

### ISSUE THREAD

**Issue by runette** [lutraconsulting/MDAL#306]
I know that MDAL is not currently supported against 3.1.3 since it supports the latest version used in QGIS - but I am sure that QGIS will move to 3.1.3 soon.

I need to build against the latest conda build of GDAL to solve a dll implosion.

ERROR

When built against the latest conda package - which is GDAL 3.1.3, the build works but `mdal_gdal_grib_test` fails for two out of three tests but with the same error related to the line

```
  int active = getActive( ds, 0 );
  EXPECT_EQ( 0, active );
```

the errors being 

```
C:\Users\runes\Documents\GitHub\MDAL\tests\test_gdal_grib.cpp(46): error: Expected equality of these values:
   0
   active
     Which is: 1
```
(and the same for line 96)

EXPECTED RESULT

To pass the tests.

PROPOSED FIX

I actually have no idea. I don't even know what that test is actually testing.

**Comment by runette** [comment]
I should add that if I comment out those tests  - all other tests pass

**Comment by PeterPetrik** [comment]
Hi, looks like GDAL 3.1.3 may read the Madagaskar wind file slightly differently or your build is broken.

**Comment by runette** [comment]
I think you. might be right :)

I don't think there is an error in the build - since the other assertions in the test script pass (so it is loading the right mesh and getting the right number of values etc) and when run in the application, the application loads the mesh.

It does look like 3.1.3 has made a small change to something. As I say - I do not actually know what that one line in the test is testing for and I don't know anything about the GRIB driver so I don't know where to start debugging this one. At the moment e are building with that assertion commented in the test script and it all seems to be working.

**Comment by runette** [comment]
I am going to close this issue - since it does not seem to happen with GDAL 3.1.4 or GDAL 3.2.0
