### ISSUE TITLE
Bad read of 0 values in SELAFIN file

### ISSUE THREAD

**Issue by ccoulet** [lutraconsulting/MDAL#316]
Hi
I noticed sometimes there is hole in the map when I display some Telemac results.
After analysis, I discover that the hole are generated where the values on node are 0.
When inspect the values, there is no_data indicate..
This could have sense for water depth as sometimes we don't want to map 0 values but this is more problematic for the bottom or the free surface when working on coasts as 0 is a real value...
Hope this could be solved in a future version

**Comment by vcloarec** [comment]
which version?

**Comment by ccoulet** [comment]
Pi

**Comment by vcloarec** [comment]
I think this is fixed with last MDAL and QGIS 3.16. Can you try?

**Comment by ccoulet** [comment]
I should update ;-)
I will try and let you know

**Comment by ccoulet** [comment]
Seams to work with 3.16. But Qgis is slower !!!

**Comment by vcloarec** [comment]
big mesh? what is slower, the rendering?

**Comment by ccoulet** [comment]
Not so big mesh.
About the slower term, it's just a feeling according to the view of my model just before the update and after.
No more investigation done

**Comment by vcloarec** [comment]
Reading of data has changed with this release, before, all the data was loaded in memory for all time steps. Now, only needed data are loaded for each time step/dataset group, so it is possible, when you change the time step or the dataset group, that rendering cold be slower, but not so much. That will depends on the mesh size and/or the speed of your access to data.

**Comment by PeterPetrik** [comment]
so if it is fixed in 3.16, we closing this ticket.
