### ISSUE TITLE
Issue with MDAL as dependency

### ISSUE THREAD

**Issue by roya0045** [lutraconsulting/MDAL#318]
Greetings, I'm not sure if this is the right place, maybe its related to something else or just a layer 8 issue.

I am attenpting to compile QGIS in another way on windows and with fresh QGIS-dev-deps and a recently rebased branch I get an error about missing MDAL LIBRARY wether I tick or not the WITH_INTERNAL_MDAL when I am generating with cmake.

I'm not sure if osgeo is missing the library, if it must be compiled on the side to compile qgis now or if something else is causing issues.

Thanks!

**Comment by PeterPetrik** [comment]
osgeo4w does not have indeed the library. you need to use internal_mdal (best to run `ccmake .` in build dir and check all MDAL vars) or compile yourself.

**Comment by roya0045** [comment]
Tried to compile, got an error building when using nmake. Ended up using the conda repo to simply get the dll. Seems ok now.
