### ISSUE TITLE
Add support for UGRID file

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#32]
[UGRID](https://github.com/ugrid-conventions/ugrid-conventions): [Delft3D Flexible Mesh Suite](https://www.deltares.nl/en/software/delft3d-flexible-mesh-suite)

**Comment by saberraz** [comment]
ping @arthurvd

**Comment by arthurvd** [comment]
Hi @saberraz @PeterPetrik , at Deltares we are actually very much interested in getting support for our Delft3D FM Suite output files in MDAL. I can assist by providing example files, and making necessary code changes on our side. 

I just did a test myself using QGIS 3.6.0-Noosa, revision 58734527ab, and the Crayfish plugin 3.1.0.
When I load an example file from our latest release, via Layer > Data Source Manager > Mesh, I get the error message:
"Invalid Data Source: d:\dam_ar\dflowfm_models\testbench\e02_dflowfm_svn\f12_inout\c080_ugrid_mapseriesonevalue\dflowfmoutput\simplebox_hex7_map.nc is not a valid or recognized data source."

What would be the next stap in diagnosing the cause of this?

**Comment by PeterPetrik** [comment]
Full CF conventions will be covered in #116
