### ISSUE TITLE
SWW mesh layer not displaying time slices

### ISSUE THREAD

**Issue by stoiver** [lutraconsulting/MDAL#328]
Not sure if this is an mdal or qgis issue. I have just installed the version 3.16.1 version of QGIS on windows. I loaded an sww file which worked reasonably well, except that there is no slider available to change timeslices.

**Comment by PeterPetrik** [comment]
Hi, could you please share the file with us? Also/Or can you try to run `ncdump -h <your file>.sww` and post here the result? (to check if you test has a time at all -> number_of_timesteps dimension)

Peter

**Comment by stoiver** [comment]
@PeterPetrik Linked are the output of `ncdump -h`  on the original sww file where I first saw the problem and a smaller problem and a screendump of qgis for the smaller file. 

The first sww file is too large to upload. I do notice that the time variable is set as double instead of float. It is a more recent sww file with the centroid data (the _c variables). I also tried a very old sww file [cairns.sww](https://github.com/lutraconsulting/MDAL/blob/master/tests/data/sww/anuga-viewer/cairns.sww)  which you have in your MDAL tests and it too has the problem when viewed as a mesh layer on QGIS 3.16.1 (see the screendump below).

[cairns_ncdump.txt](https://github.com/lutraconsulting/MDAL/files/5698817/cairns_ncdump.txt)
[merewether_ncdump.txt](https://github.com/lutraconsulting/MDAL/files/5698818/merewether_ncdump.txt)

![qgis_cairns_screendump](https://user-images.githubusercontent.com/5563684/102276832-7f0cba80-3f7b-11eb-8474-e692b4065e8e.jpg)

**Comment by vcloarec** [comment]
Hello, do you talk about the time slider under the dataset groups widget?
In this case, this one is not existing any more since temporal is integrated for all layers (since 3.14).
You have to activate the temporal controller (the clock in the tool bar).

**Comment by saberraz** [comment]
QGIS comes with a global Temporal controller. Please use that to see the mesh time series:
https://www.qgis.org/en/site/forusers/visualchangelog314/index.html#temporal

**Comment by stoiver** [comment]
@PeterPetrik @saberraz and @vcloarec thanks for the pointer to the temporal controller. Of course that was my problem. I had been sticking to QGIS 2.18 as the last time I tried version 3 of QGIS there was that problem with sww files crashing QGIS (due to the centroid data in the sww file). So great to see that everything is working well now. Thanks so much for supporting sww files. Great job. 

There is a small problem with the QGIS online help https://docs.qgis.org/3.16/en/docs/user_manual/working_with_mesh/mesh_properties.html in particular section 16.3.3.3. The figure has the old time controller. Might be good to update that figure and put in a pointer to the new time controller. 

Thanks again 
@stoiver
