### ISSUE TITLE
add support for XDMF format

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#33]
Generic format for scientific data.

**Comment by saberraz** [comment]
ping @sebbelese

**Comment by kastepha** [comment]
Is it planned the provide XDMF support in the near future?

**Comment by saberraz** [comment]
If you are interested in funding the work, please contact us.

**Comment by PeterPetrik** [comment]
related/duplicate of https://github.com/lutraconsulting/MDAL/issues/82
