### ISSUE TITLE
Problem with building 0.8.0 for Conda

### ISSUE THREAD

**Issue by runette** [lutraconsulting/MDAL#339]
I have been trying to get the conda-forge feedstock for version 0.8.0 working and I keep getting this error:

```
CMake Error at external_drivers/CMakeLists.txt:10 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source "dhi_dfsuz" which is not an existing
  directory.
```

building off the release releases 0.8.0 .zip image and using this command ( the same as 0.7)

```

cmake  ^
	-DCMAKE_BUILD_TYPE=Release  ^
	-DENABLE_TESTS=OFF ^
	-DNETCDF_PREFIX="%LIBRARY_PREFIX%" ^
	-DHDF5_ROOT="%LIBRARY_PREFIX%" ^
	-DGDAL_DIR="%LIBRARY_PREFIX%" ^
	-DGDAL_LIBRARY="%LIBRARY_PREFIX%\lib\gdal_i.lib" ^
	-DGDAL_INCLUDE_DIR="%LIBRARY_PREFIX%\include" ^
	-DLIBXML2_LIBRARIES="%LIBRARY_PREFIX%\lib\libxml2.lib" ^
	-DLIBXML2_INCLUDE_DIR="%LIBRARY_PREFIX%\include\libxml2" ^
	-DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
	-DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
	..
if errorlevel 1 exit /b 1
```

It seems clear this is related to the new DFSU functionality but I cannot work what the problem is.

**Comment by PeterPetrik** [comment]
that driver is only on windows and even there you need to have propriatory SDK on the system. I would build it without the external DFSU driver in conde

add 

`-D EXTERNAL_DRIVER_DHI_DFSU=OFF` to the conda script

**Comment by runette** [comment]
Aha - that is a new and undocumented compile-time switch. You probably want to update the documentation
