### ISSUE TITLE
MDAL using debug versions of VS C++ redistributables

### ISSUE THREAD

**Issue by runette** [lutraconsulting/MDAL#343]
It have become aware (i.e. when trying to distribute my application) that the Conda compile of MDAL and therefore I believe the standard compile as well (although I have not tested) creates a dependency to the Debug versions of the C++ redistributable on Windows - rather than the release version that most people have installed and is included in Conda. 

I.e. it is dependent on :
- vcruntime140d.dll
- ucrtbased.dll
- msvcp140d.dll

rather than:
- vcruntime140.dll
- ucrtbase.dll
- msvcp140.dll

The conda build script [see here](https://github.com/conda-forge/mdal-feedstock/blob/master/recipe/bld.bat) is not significantly different from the one provided in the readme - except for having `-DCMAKE_BUILD_TYPE=Release`!

I did always think it was funny that the binaries end up in a `Debug` folder.

This is a bit of a pain when it comes to redistribution. Does anyone know how to change this?

**Comment by PeterPetrik** [comment]
it is problem of compilation, not `CMake`. On Windows I think you generate all types of builds (release, debug, ...) ini one folder (compared to linux/mac where you have one build folder per type) and you need to choose when building what you want to build. By default debug. see 

https://stackoverflow.com/a/20423820/2838364

this needs to be changed 

https://github.com/conda-forge/mdal-feedstock/blob/f67a2675f715705dc4b4bbe9c857e4c494313667/recipe/bld.bat#L23

to 

`cmake --build . --config Release`

**Comment by runette** [comment]
Thanks - I will take a look

**Comment by runette** [comment]
Fixed in https://github.com/conda-forge/mdal-feedstock/pull/11.

PR #345 added to update docs

**Comment by runette** [comment]
Note for the record - this is only fixed in Conda for the 0.8.0 build running on GDL 3.2.2 (and later). The earlier builds will not be fixed.
