### ISSUE TITLE
Import of NetCDF fails upon order of variables

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#347]
see https://github.com/qgis/QGIS/issues/42552

@raphaeljolivet

**Comment by PeterPetrik** [comment]
MDAL is not fully compatible with the CF-conventions (check the list https://github.com/lutraconsulting/MDAL#supported-formats), but it *should* be compatible with UGRID conventions. For CF-conventions, there are some cases where it is not parsed correctly or at all (e.g. typical example is when there are just points without time dimensions).

related to 
#237
#130
#248

**Comment by sureshphdau** [comment]
I too had similar issue in reading UGRID file in Netcdf format. The data file is produced from Delft3D software as output with multiple parameters. When I try to load using mesh option, it only loads one parameter out of multiple parameter. The data file is a 2D with single level data and no vertical layers. I can share the sample file if required. 
Please suggest the solution.

**Comment by PeterPetrik** [comment]
@sureshphdau may be different problem. Please attach the (minimal) example file that shows your issue.

**Comment by sureshphdau** [comment]
@PeterPetrik Thanks a lot for the response. Below is the link to the example data file that I am working with. 
https://we.tl/t-E7DLmxs1eY

**Comment by vcloarec** [comment]
@sureshphdau , Maybe the link is expired, can you share again your data?
