### ISSUE TITLE
Legend bug after loading a project with MDAL layer

### ISSUE THREAD

**Issue by ccoulet** [lutraconsulting/MDAL#351]
Hi
I save a project which contain a layout.
In this project I had 4 MDAL layers. Different results but with the same parameters.
I define the color map (saved in a dedicated file in order to be reused)
When I first use the layout everything is ok but after loading the project, the layout doesn't have the color map in the legend...
In 3.16 the variable and the color ramp is not available in the layer selector
In 3.18 and 3.19 this is available but not in accordance with the map...

**Comment by saberraz** [comment]
This is best filed in QGIS repo:

**Comment by ccoulet** [comment]
submitted!
