### ISSUE TITLE
Open error of binary .DAT file

### ISSUE THREAD

**Issue by msorockin** [lutraconsulting/MDAL#354]
New versions of QGIS 3.16 and 3.18 with new MDAL crashs when try assign dataset to mesh from binary .DAT file.
But older versions of QGIS could it. I did it with QGIS 3.10.
I tried to investigate this issue and I suppose that problem is with open of files without status flags.

**Comment by PeterPetrik** [comment]
can you please give us an example file to test against?

**Comment by msorockin** [comment]
Dear Peter
Thank you for your response.
Send you mesh and result files of Test 2 – Filling of Floodplain
Depressions from EA benchmarks
https://www.gov.uk/government/publications/benchmarking-the-latest-generation-of-2d-hydraulicflood-modelling-packages

ср, 19 мая 2021 г. в 09:54, Peter Petrik ***@***.***>:
