### ISSUE TITLE
Reload mesh on refresh

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/MDAL#36]
csv and shapefile layers re-read the data from disk when pressing F5. This currently does not work with meshes.

**Comment by saberraz** [comment]
Is that related to Crayfish plot?

**Comment by michelk** [comment]
No, when I edit a mesh with an external program and write it to disk. I would be great, if I press F5 in QGIS 3 then the mesh would be reloaded.

**Comment by saberraz** [comment]
Great. In that case, it is a QGIS bug. I have opened a bug in QGIS:
https://issues.qgis.org/issues/20124

**Comment by michelk** [comment]
Thanks Saber.
