### ISSUE TITLE
Feature Request: Show elevation of mesh when hover over

### ISSUE THREAD

**Issue by michelk** [lutraconsulting/MDAL#37]
In the crayfish plugin the elevation of the mesh at cursor-position was shown in the the crayfish-panel. 

It would be nice to have a similar feature in MDAL. It would also be possible to use the value tool plugin for that.

**Comment by PeterPetrik** [comment]
@michelk MDAL is just a c(c++) library that handler reading of the data from data formats. All GUI related stuff is either done in QGIS (so raise bug/enhancement) there or in Crayfish. Please read Crayfish README to find out where to raise bugs. This feature should be either part of QGIS identify tool and/or Crayfish GUI. 

If you are interested in funding the feature development, contact us on info@lutraconsulting.co.uk
