### ISSUE TITLE
[UGRID]: Cannot load Delft3D-FM Output after QGIS 3.10

### ISSUE THREAD

**Issue by dquang** [lutraconsulting/MDAL#392]
Hi there,

I would like to raise another issue that slightly related to the #227 (Delft3D-FM). After QGIS 3.10, the output from Delft3D-FM can not be loaded correctly anymore: Either the projection is wrongly interpreted (QGIS 3.12 to 3.21) or the dateset is not provided (QGIS 3.22 told that `Layer data source could not be found`). 

This problem could have something to do with the `Conventions ` that are used by the Delft3D-FM. The output from current Delft3D-FM current version, which uses `Conventions: CF-1.8 UGRID-1.0 Deltares-0.10`, can not be loaded. While the output from very old version of the Delft3D-FM, which uses `Conventions: UGRID-0.9` can be loaded normally (also in QGIS 3.22). It is interesting that the output with new Conventions has no problem in QGIS 3.10.

I have attached two sample data, one is the output from old Delft3D-FM Version and one is from new version ([sample.zip](https://github.com/lutraconsulting/MDAL/files/7625362/sample.zip)). I'm sorry that the sample data is bigger than 3Mb (ca. 6Mb each)

Could you please so kind to take a look? Thank you very much!

Regards
Quang

**Comment by saberraz** [comment]
Hi, I can confirm the issue.

**Comment by dquang** [comment]
Hi Vincent @vcloarec, the attached files do not have the same mesh. I attached both of them because QGIS-3.10.0 can open both of them but QGIS-3.22 cannot open none of them. For your investigation, I think you should use the file *sampleNew.nc*. Following are QGIS-3.10.0 Info on my Computer:


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>


QGIS version | 3.10.0-A Coruña | QGIS code revision | 6ffa89eb3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)

</body></html>

**Comment by vcloarec** [comment]
@dquang can you give the count of vertices/faces if this mesh.

**Comment by dquang** [comment]
@vcloarec, for sampleNew.nc: 

- Number of faces: 16769
- Number of nodes: 11200
- Number of edges: 27968

**Comment by vcloarec** [comment]
Got it:
![image](https://user-images.githubusercontent.com/7416892/148772885-e33a8120-39d4-4d2b-8abf-829f63d749df.png)
But here it is the bed elevation I find a bit weird... Is it of for you?

**Comment by dquang** [comment]
@vcloarec, fantastic! Thank you very much! It is ok like that. Other non-geometry variables are on the side of Deltares!
