### ISSUE TITLE
Support for H2i format

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#399]
Examples below show the topography grid with no quantity:
https://github.com/d2hydro/H2i_code_factory/tree/main/data/de_tol_full/grids

**Comment by saberraz** [comment]
- Lazy loading should be supported for this format.
- The spec is being finalised
- There will be a json file containing metadata

**Comment by saberraz** [comment]
Some more info:
You can find draft spec documentation here: https://github.com/d2hydro/H2i_code_factory/blob/main/docs/data_format.md
The small test-model with topology + results can be found here: https://github.com/d2hydro/H2i_code_factory/tree/main/data/de_tol_small

metadata.json comes with a json-schema you can find here: https://github.com/d2hydro/H2i_code_factory/blob/main/json-schemas/metadata-schema.json

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/MDAL/commit/b7e124fd910f2bcd4b8e5f67abfd0d8ddf4976c7
