### ISSUE TITLE
.dat Format not Recognized in QGIS

### ISSUE THREAD

**Issue by mattrjackson** [lutraconsulting/MDAL#41]
It appears the loader (MDAL::Loader::load) does not attempt to load the binary or ascii .dat file formats. Thus when QGIS attempts to load a .dat mesh, it errors out and says it's an unrecognized format.

**Comment by saberraz** [comment]
DAT files are a part of 2dm. So, you need to first open the 2dm > right-click > open properties > under Source tab > Assign Extra Dataset to Mesh file
And load your DAT or XMDF files.

I am closing this ticket. For opening new tickets please see the table here:
https://github.com/lutraconsulting/qgis-crayfish-plugin#crayfish-3-vs-crayfish-2

(e.g. your ticket is a QGIS ticket).
