### ISSUE TITLE
Problem with UGRID to load file if directory contains special char

### ISSUE THREAD

**Issue by ccoulet** [lutraconsulting/MDAL#428]
Hi
I'm an old school informatic user so I often create directory and file without any spaces but with shared space, I'm not always the decider...
I recently encountered a problem with a netcdf ugrid file which is well open by QGIS/MDAL when located on my computer and where a crash occur if I open the same file located on a server.
The only difference I saw is the name of the path which contains spaces on the server architecture.
As other files (gpkg, shp, ...) are well opened by QGIS, I suspect this in an internal problem in MDAL but this need to be confirmed and potentially corrected
Thanks in advance

**Comment by ccoulet** [comment]
Hi Vincent
Latest version of Qgis (3.26.2)
Load from Data Source Manager
For the path (with some adaptation for confidentiality reasons)
It works with this path
D:\Documents\coulet\Travail\xxxx_xxxxxxxxxxxxxxxxx\xx_xxxx\Calculs_xxx\Resultats\max_x_xxxx_x.xxxx.nc

and crash with this one:
D:\Documents\coulet\xxxx\xxx xxxxxxxxxx - 04-Données xxxxxxxxxxxxx xx xxxxxx\03_Travail\01_xxxxxxxxxx_xxxxxxxx_xxx\Calculs_xxx\Resultats\max_x_xxxx_x.xxxx.nc

**Comment by ccoulet** [comment]
I realized that there is also a "é" which could probably be a potential source of problem.

**Comment by vcloarec** [comment]
I confirm an issue under Windows, not leading to a crash, but the file is not recognized as a UGRID file when the path contains "é". But with space it is OK.

**Comment by ccoulet** [comment]
Thanks for investigate this problem

**Comment by vcloarec** [comment]
@ccoulet , #429 could fix your issue, but I am not complety sure...

**Comment by ccoulet** [comment]
I will see in the next version.
Thanks for your investment.

**Comment by vcloarec** [comment]
@ccoulet Have you try with new version of QGIS?

**Comment by ccoulet** [comment]
Sounds working!
Thanks
