### ISSUE TITLE
Cant open sww files in QGIS 3.26.0-Buenos Aires

### ISSUE THREAD

**Issue by stoiver** [lutraconsulting/MDAL#431]
Just tried to load in an sww mesh file in QGIS 3.26.0 (installed on WSL via conda-forge). 

When trying to open a mesh file the file format and the file opener gui only gives options for 2DM, Selafin, Stanford ply, and UGRID.

**Comment by runette** [comment]
I tried on 3.26.3 on Mac and all formats were available.

**Comment by stoiver** [comment]
@runette that is interesting. I just downloaded the windows version (3.26.3) and observed the same problem.

**Comment by vcloarec** [comment]
Hi,
Maybe be you try to create a new mesh layer instead of loading one? I ask because the format you can see are all the format that can be written by MDAL. Can make a screen shot of the window you use?

**Comment by stoiver** [comment]
@vcloarec, You are right. I was picking the "create a new mesh layer" not the "add layer".
