### ISSUE TITLE
[gdal driver] Bug in vector components identification (Eastward vs Northward)

### ISSUE THREAD

**Issue by marceloandrioni** [lutraconsulting/MDAL#444]
Hello, I believe there is a bug in the routine that identifies the U and V components of a vector. I checked the code and it's my understanding that the Eastward and Northward components are swapped in lines:

https://github.com/lutraconsulting/MDAL/blob/master/mdal/frmts/mdal_gdal.cpp#L653
https://github.com/lutraconsulting/MDAL/blob/master/mdal/frmts/mdal_gdal.cpp#L665
https://github.com/lutraconsulting/MDAL/blob/master/mdal/frmts/mdal_gdal.cpp#L684
https://github.com/lutraconsulting/MDAL/blob/master/mdal/frmts/mdal_gdal.cpp#L685

Also, I  would like to make a few suggestions:

-  the above lines could check for names that **contains** the strings eastward/northward, not just names that **start with**, e.g.:

`MDAL::contains( band_name, "Eastward", MDAL::CaseInsensitive ) ||`
instead of 
`MDAL::startsWith( band_name, "Eastward", MDAL::CaseInsensitive ) ||`
This would help with names like `barotropic eastward velocity` and `barotropic northward velocity`. Searching the [CF Conventions standard name table](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html) for eastward/northward, shows a lot of variables that have these sub-strings at the start or middle of the string.

- include
`MDAL::contains( band_name, "zonal component", MDAL::CaseInsensitive ) ||`
`MDAL::contains( band_name, "zonal", MDAL::CaseInsensitive ) ||`
and
`MDAL::contains( band_name, "meridional component", MDAL::CaseInsensitive ) ||`
`MDAL::contains( band_name, "meridional", MDAL::CaseInsensitive ) ||`
when checking variables names (with zonal==u/x and meridional=v/y)
This would help with names like `zonal component of current` and `meridional component of current`.

- apply these same rules when checking names for UGRID datasets [here](https://github.com/lutraconsulting/MDAL/blob/master/mdal/frmts/mdal_ugrid.cpp#L523)
I believe there is some typos in this file, e.g.:
`name = MDAL::replace( longName, ", x-component", "" );`
please notice the comma before `x-component`.

I could do a PR with these changes if it's okay with you.

Below an example showing a dataset with variables "Eastward Water Velocity" and "Northward Water Velocity" loaded in the original (hycom.png) and with variables swapped (hycom2.png) to account for the identification problem. One can see that in the file with the u/v variables swapped, the current flow is correct.
![hycom](https://user-images.githubusercontent.com/13545615/218566630-cd7388bc-2a0c-40ab-9ed1-acc5a78d8efa.png)
![hycom2](https://user-images.githubusercontent.com/13545615/218566640-07656fbd-1282-4ba7-9690-15b58b079509.png)

**Comment by PeterPetrik** [comment]
Hmm, looks really like switched variables

If you can make PR it would be great. Thanks

**Comment by uclaros** [comment]
Should be fixed with #445
