### ISSUE TITLE
[PLY] Saved mesh with PLY format seems incompatible with some other mesh reader

### ISSUE THREAD

**Issue by vcloarec** [lutraconsulting/MDAL#450]
see https://github.com/qgis/QGIS/issues/52467

**Comment by runette** [comment]
You can assign that to me. There is another PLY issue I have been meaning to raise - I will do that and then cover both

**Comment by runette** [comment]
@vcloarec - when do you plan to push he next version? Just wondering how much time I have :)

**Comment by vcloarec** [comment]
Nothing is planned for now, still there are not big changes... and I am not sure we will backport this changes. So we can say that it could be good to have PLY fixes for the next release of QGIS, that is the end of May.
