### ISSUE TITLE
MIKE (dfs2) file format

### ISSUE THREAD

**Issue by Prashant-M-Soni** [lutraconsulting/MDAL#478]
Hello experts,

I want to understand the format of a dfs2 file in MIKE, i.e the header title along all axes in order to arrange my data appropriately.

I expect some expert will definitely extend a help in this regard.
Thanks

**Comment by saberraz** [comment]
Hi, best to post this question to the MDAL mailing list. I am closing this ticket as it is not an issue or a feature request.
