### ISSUE TITLE
Support TIF folder

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/MDAL#58]
multiple TIF files in one folder
one TIF - one time

**Comment by saberraz** [comment]
I think that is beyond MDAL. 

What will be good though to have is: a processing tool to convert between GDAL and MDAL

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/release-2.7.2/corelib/frmts/crayfish_tifs.cpp

**Comment by saberraz** [comment]
Wouldn't it better to have a processing alg to create virtual mesh layer, as per Martin's suggestion?

**Comment by wonder-sk** [comment]
yeah I think this virtual mesh approach would be the best... and a processing alg to build a virtual mesh definition from TIF folder could have plenty of options e.g. how the date/time gets parsed
