### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by ccoulet** [lutraconsulting/MDAL#65]
When I try to compile MDAL, I receive an error message about the file mdal_config.hpp which is missing in the repository.
Could we comment the include without any risks?
Regards

**Comment by PeterPetrik** [comment]
Hi, 

`mdal_config.hpp` si autogenerated file by CMake, see https://github.com/lutraconsulting/MDAL/blob/58ef371c99562b94fc9ee5027edcb37f26ed48f3/CMakeLists.txt#L67

you need to create cmake's build system that will generate this file automatically in the build directory. Do you use CMake for building?

**Comment by ccoulet** [comment]
I use CMake with Gui but I made an error in the working directory (taking MDAL/mdal instead of just MDAL)
It works now!
Thanks a lot
