### ISSUE TITLE
Problem opening mesh layer in QGIS as user

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/MDAL#72]
Trying to open a mesh layer as user fails in QGIS with the following error:
![unnamed](https://user-images.githubusercontent.com/2649047/50849753-cb065c00-136f-11e9-8553-b88e7a978708.png)
But when you run QGIS as admin, the same layer can be loaded. Note, this happened for a 2dm file.

**Comment by PeterPetrik** [comment]
workaround is to run QGIS as admin user.

**Comment by saberraz** [comment]
This is not a really workaround for most of users in an enterprise environment. Beside, it might mess up QGIS user's profile.

**Comment by PeterPetrik** [comment]
it is when creating spatial index for QGIS mesh triangular mesh, somehow this is called https://github.com/libspatialindex/libspatialindex/blob/c303dd6c99e23c2d59d21c1c1357002bfc925308/src/tools/Tools.cc#L995 and it creates the temporary spatial index in the temp files

**Comment by saberraz** [comment]
The issue is due to spatialindex library is trying to write the index to the disk for large files. For smaller files, it works as the index is done in memory. But for larger files, it will write the index files under the Current Directory. So, if user does not have write access, it will give the error.

**Comment by saberraz** [comment]
@PeterPetrik isn't it a better to have an option under Properties for users to create the spatial index as a file, similar to Vectors. So:
- You get a persistent spatial index and does not need to be regenerated upon loading files
- Will resolve this issue.

**Comment by PeterPetrik** [comment]
**WORKAROUND**: ok, so to run QGIS as user, one needs to start it from a working directory with the write rights. For example when QGIS is started by shortcut or batch file from some system/unwritable folder the error when loading the mesh can occur

**Comment by saberraz** [comment]
To expand on @PeterPetrik workaround:
1- Create a shortcut to QGIS.bat on your desktop
2- Write click on the shortcut and open the Properties
3- Set the working directory to a folder you have permission to write to

**Comment by AGBNE** [comment]
The workaround was applied (as were all other suggestions) as per the above comments. The loading of xmdf (>2GB) still returns a "Bad Allocation". QGIS 3.4.4-Madeira.

**Comment by saberraz** [comment]
@AGBNE there has been major changes for spatial indexing in QGIS 3.5. Could you try with QGIS weekly/nightly builds?

**Comment by AGBNE** [comment]
You little ripper ! my XMDF can load without error. Thanks @saberraz 
Loaded "29 Jan nightly build", altered the "Start In" directory in the desktop short cut.
#mademyfriday

**Comment by saberraz** [comment]
With the latest improvements, our tests show 70-80% improvement in loading 2dm files.

**Comment by Neeestoor** [comment]
I have the same problem with QGIS 3.6.2 in OSX
Can you please help?
![image](https://user-images.githubusercontent.com/50637804/57725944-fb2e7600-7653-11e9-9272-70faba5e7fda.png)
After the error QGIS stop rendering any layer.

**Comment by PeterPetrik** [comment]
@Neeestoor can you please specify:

- which QGIS, MDAL, spatialindex versiou do you use?
- which OS do you use
- How do you start QGIS (see https://github.com/lutraconsulting/MDAL/issues/72#issuecomment-453056157)

**Comment by Neeestoor** [comment]
@PeterPetrik I start QGIS by clicking the dock icon. I tried to do the shortcut thing, but I get the same error.
MDAL... I suppose is the Crayfish version? At least I did the mesh as shown in this tutorial (https://www.youtube.com/watch?v=qN_UC0AZhVM) (Just... to load the is through layer menu... QGIS browser doesn't show the file)
Is spatial index the crs? WGS 84 UTM 12N.

<img width="895" alt="Captura de Pantalla 2019-05-15 a la(s) 10 24 41" src="https://user-images.githubusercontent.com/50637804/57788503-d510e080-76fc-11e9-9194-304a4e246989.png">
<img width="190" alt="Captura de Pantalla 2019-05-15 a la(s) 10 25 21" src="https://user-images.githubusercontent.com/50637804/57788506-d6420d80-76fc-11e9-8f95-50f31ba388e9.png">

**Comment by PeterPetrik** [comment]
do you use official mac package or https://lutraconsulting.github.io/qgis-mac-packager/ ?

**Comment by Neeestoor** [comment]
I downloaded QGIS from the QGIS's website. (
https://qgis.org/es/site/forusers/download.html) and Python from Python's
website.

**Comment by saberraz** [comment]
See: https://trac.osgeo.org/osgeo4w/ticket/603#ticket

**Comment by saberraz** [comment]
Fixed in:
https://github.com/qgis/QGIS/commit/a4645f695479b215abbe97acfa34f7adc506fd2c and https://github.com/qgis/QGIS/commit/3c57d28cfabf615f29af51a332db5ef51bd191f0
thanks to @jef-n
