### ISSUE TITLE
Support for MIKE (dfs2) format

### ISSUE THREAD

**Issue by nyalldawson** [lutraconsulting/MDAL#78]
Would be nice to see support for the mike dfs2 format.

**Comment by PeterPetrik** [comment]
@nyalldawson Do you know if it was supported by crayfish 2 (QGIS 2.x)? If not, do you have some specification of the file. Also do you have an example output files (ideally size < 3mb) that can be added to the test suite?

**Comment by nyalldawson** [comment]
Let me see what I can find. I've struggled to find any documentation on the format, so was hoping you had encountered this before and already had some knowledge of it :wink:

**Comment by PeterPetrik** [comment]
:) Saber is our hero for test cases. @saberraz do you know something about dfs2?

**Comment by saberraz** [comment]
I have come across this document for format:
http://manuals.mikepoweredbydhi.help/2017/General/FM_FileSpecification.pdf
and also some a conversion tool to netcdf:
https://github.com/pwcazenave/dhi-toolbox/blob/master/dfsu2nc.m

@DHI and @JesperGr know more...

**Comment by JesperGr** [comment]
The DFS file format is not open. There is an API for accessing file content. The API is publicly available for C#, distributed when installing the MIKE SDK. 

Examples and more documentation from:
http://docs.mikepoweredbydhi.com/core_libraries/core-libraries/

I also just put the MIKE Core examples on GitHub
https://github.com/DHI/MIKECore-Examples

To integrate it in MDAL, I guess you would need a C++ API for accessing file content, right?

**Comment by saberraz** [comment]
thanks a lot @JesperGr for the example files, much appreciated.
For accessing the files, I leave @PeterPetrik to comment, but ideally we want direct access to the file without any SDK (as I presume your SDK is platform dependant and not available in Linux/macOS)?

**Comment by nyalldawson** [comment]
@JesperGr Just to expand on the desired use case here -- I have a client who is using MIKE for modelling, but who uses QGIS as their main desktop GIS application (and for data management workflows). They are wanting to take advantage of all the recent developments in QGIS and Crayfish and utilise them directly with MIKE, but currently they are being locked out of this approach due to the locked down DFS file format (and honestly, are being pushed to alternative modelling software as a result).

I personally can only see benefits (both for end users, and for DHI!) in the DFS file format being an open specification which is easily readable and writable by tools like MDAL, QGIS and Crayfish. It just makes MIKE a much more compelling product when it can be used as part of a larger software ecosystem.

**Comment by PeterPetrik** [comment]
@JesperGr As for the integration of MDAL with 3rd party libraries, we use plain C-API for HDF5, GDAL, etc.. However if your library for reading DFS file format is closed source, not compatible with MIT (MDAL) and/or GPL2(QGIS) licensing, it may be very difficult for users to use it in QGIS (similarly to GDAL and support of various extra plugins). 

If this is the case, we cannot ship it by default with the rest of the (open) drivers. So to use it in QGIS, users will need to compile/fetch the shared driver for DFS format and add it to the installation manually.

Moreover, in MDAL we do not use shared-libraries/plug-and-play format drivers. This would need to be implemented similarly to QGIS/GDAL solution. 

As @nyalldawson mentioned, open-sourcing the format (so we can implement reader in MDAL directly) or writing a new C(or C++) library for reading the format with GPL2/MIT licence would solve the issues.

**Comment by PeterPetrik** [comment]
.dfs2 is our gridded format (similar to .asc). There exists a tool to convert dfs2 to ASC.

**Comment by maximlt** [comment]
There is indeed a tool in the Mike Zero Toolbox to convert .dfs2 files to .asc files, it is called Mike2Grid. However, be aware that it works only if the grid in the dfs2 file has a 0-deg orientation (it is common to rotate a computation grid according to the expected flow direction) and the same X- and Y-dimensions.

**Comment by saberraz** [comment]
Unfortunately, this issue is blocked upstream as the proposed solution by @JesperGr is not an option in QGIS/MDAL.

We hope @DHI will change their position and share the format specifications freely, so that other software packages can interact with their outputs.

**Comment by saberraz** [comment]
See:
https://github.com/DHI/mikeio

**Comment by PeterPetrik** [comment]
fixed in https://github.com/lutraconsulting/MDAL/pull/377
