### ISSUE TITLE
BASEMENT output .dat error

### ISSUE THREAD

**Issue by JoaoBarreiro** [lutraconsulting/MDAL#91]
I've been working with BASEMENT and up to now the visualization on Crayfish was fine. With QGIS update to v3.4 and the MDAL tool I'm struggling in visualizing BASEMENT outputs in qgis. When trying to add both ascii.dat  or *.sol files as extra dataset to the 2dm mesh,  the message "Could not read mesh dataset." appears.
Actually, by reading these output files, the *.sol files are written in the *.dat syntax, but I am unable to upload them on MDAL as extra dataset.

**Comment by saberraz** [comment]
Hi @JoaoBarreiro 

Supporting BASEMENT for MDAL is in the pipeline and should be ready for QGIS 3.8 release (earlier probably in April in QGIS 3.7).

**Comment by PeterPetrik** [comment]
@saberraz I am not sure it is the same issue. Basic BASEMENT files should be already supported. @JoaoBarreiro can you please attach a sample dataset file with 2dm that is not working properly? Ideally if the files have < 3MB in total together so we can add them to the test suite. (just run the model with few dozens/hundreds cells and just few timesteps)

**Comment by JoaoBarreiro** [comment]
@PeterPetrik it is hard to me to "crop" the mesh since BASEmesh plugin (from BASEMENT) is also facing some problems due to qgis newest versions, but here is the compelte mesh (it is a "urban" mesh).
[2dm.zip](https://github.com/lutraconsulting/MDAL/files/2859652/2dm.zip)
But from tour suggestion, it seems like the problem is from the 2dm and not from the output files?

**Comment by JoaoBarreiro** [comment]
@PeterPetrik. sorry, do you have any clue of what might be the problem?

**Comment by PeterPetrik** [comment]
@JoaoBarreiro Hi, I will work on BASEMENT probably later next month. If you need BASEMENT support for your file for your work immediately, consider commercial support with us https://www.lutraconsulting.co.uk/qgissupport .

**Comment by kastepha** [comment]
@JoaoBarreiro It's a known issue to us that there is no support for BASMENT result files in QGIS 3.4 MDAL at the moment. As @PeterPetrik mentioned, lutraconsulting will we working on this soon. The problem does not arise from the 2dm file, its the syntax of the *.sol file which is not supported yet. To me, it seem like minor changes could solve tis issue for example, if you change the first line of the *.sol file from "DATASET" to "SCALAR" you can add the dataset without error message.

**Comment by JoaoBarreiro** [comment]
@PeterPetrik thanks, I am looking forward for those improvements on BASEMENT outputs raeding in qgis!
@kastepha, I did change "DATASET" to "SCALAR" and added the dataset! There is still an issue with the time bar... one step at a time! If you have any tip in this, it would be useful! Anyway, many thanks for the support!

**Comment by kastepha** [comment]
Yes just realized the issue with the timestep. As a quick hack, you can modify the Lines including TS:

in the current *.sol flie, replace "TS"space"0"tap"output timestep" 
by 
"TS"space tap"output timestep" 

so without the additional "0" for every output timestep, than it shoukd work!

**Comment by JoaoBarreiro** [comment]
> m

Many thanks, it's now working fine!

**Comment by PeterPetrik** [comment]
@JoaoBarreiro which version of MDAL do you use? I can open .sol file without any problem with mdal 0.2.0 (part of QGIS 3.5 master/3.6 upcoming release tomorrow). I think the issue may already be fixed by https://github.com/lutraconsulting/MDAL/pull/77

**Comment by JoaoBarreiro** [comment]
@PeterPetrik, I'm using qgis 3.4.4. As the new version will get available tomorrow, I will install it and try to read the .sol files. I'll report here to say if I was successful or not...

**Comment by kastepha** [comment]
In the new QGIS version 3.6.0 assigment of BASEMENT *.sol files to a mesh layer works fine without any workarounds mentioned above 👍
