### ISSUE TITLE
NetCDF required for GRIB?

### ISSUE THREAD

**Issue by nyalldawson** [lutraconsulting/MDAL#92]
Current the gdal grib driver is only loaded if netcdf support is available: https://github.com/lutraconsulting/MDAL/blob/master/mdal/mdal_driver_manager.cpp#L132 

Is this correct? I think it should depend on gdal support alone, which is how the cmake rules are defined.

**Comment by PeterPetrik** [comment]
looks like it is a bug. fixed!
