### ISSUE TITLE
detect installed gtest

### ISSUE THREAD

**Issue by landryb** [lutraconsulting/MDAL#95]
tests/CMakeLists.txt fetches gtest source during configure, which is often a big no-no for distributors packaging software where sources have to be fetched separately from the build process which has no network access.

it'd be nice to detect an installed gtest version and use that one instead :)

(on a sidenote, MDAL 0.2.0 builds and installs fine on OpenBSD, i just have a local patch to add versioning to the library soname)

**Comment by PeterPetrik** [comment]
great! @landryb would it be possible to create PR for the patch or update READMe with instructions for building on that platform?

do you need to build tests at all for packaging, I think you can use `-DENABLE_TESTS=OFF` to just completely avoid tests building

**Comment by PeterPetrik** [comment]
as a sidenote for gtest, I remember that there are some issues if you do not build it from source and try to use system installation, but I would need to google it again

**Comment by landryb** [comment]
There are no particular instructions for OpenBSD, i'm just packaging it.

As for the tests, for now i disabled them but it's always nice to be able to build and run them (not by default, but for packagers it's useful to check for regressions)

Many other cmake projects make use of gtest and are able to use a systemwide installation, https://msgpack.org/ might be an example, cf https://github.com/msgpack/msgpack-c/blob/master/test/CMakeLists.txt
