### ISSUE TITLE
Use arrows of mesh renderer for flow direction rasters

### ISSUE THREAD

**Issue by jvdkwast** [lutraconsulting/MDAL#97]
Would it be possible to use the mesh arrow renderer for visualisation of Flow Direction rasters in QGIS?
Here's a video explaining flow direction in QGIS: https://youtu.be/ZLUjSEK-nbg (Minute 12-15).
The flow direction grid is generated with using the processing toolbox SAGA->Terrain Analysis->Channel network and drainage basins. But this can also be done with other tools. Different tools give a different encoding of flow direction: https://gis.stackexchange.com/questions/254939/legend-of-flow-direction-calculated-with-processing-toolbox-qgis-saga
Here's a subset from the output of the SAGA tool: https://www.dropbox.com/s/j2a0qmlphr0ezrr/flowdir_saga_subset.tif?dl=0

**Comment by saberraz** [comment]
@jvdkwast I think we need a processing algorithm to generate virtual mesh layer from rasters. See also #58

**Comment by PeterPetrik** [comment]
will be supported by processing alg in Crayfish 3.1.1+ (https://github.com/lutraconsulting/qgis-crayfish-plugin/commit/70bb47e363cbc50faec6a7dde2eff994889463dd)
